CREATE TABLE maestro_mano_obra (
  id uuid primary key default gen_random_uuid(),
  nic VARCHAR NULL,
  orden VARCHAR NULL,
  contrata VARCHAR NULL,
  territorio VARCHAR NULL,
  zona VARCHAR NULL,
  municipio VARCHAR NULL,
  corregimiento VARCHAR NULL,
  localidad_barrio VARCHAR NULL,
  tarifa VARCHAR NULL,
  tipo_actividad VARCHAR NULL,
  actividad VARCHAR NULL,
  direccion varchar NULL,
  id_transformador VARCHAR NULL,
  id_circuito VARCHAR NULL,
  num_medidor VARCHAR NULL,
  marca_medidor VARCHAR NULL,
  deuda_act double precision NULL,
  deuda_cierre double precision NULL,
  cant_factura_act INT NULL,
  cant_factura_cierre INT NULL,
  tipo_os VARCHAR NULL,
  descripcion_tipo_os varchar NULL,
  tipo_suspension_solicitada VARCHAR NULL,
  tipo_brigada VARCHAR NULL,
  id_tecnico VARCHAR NULL,
  tecnico VARCHAR NULL,
  av_resultado VARCHAR NULL,
  accion VARCHAR NULL,
  subaccion_subanomalia VARCHAR NULL,
  estado_osf VARCHAR NULL,
  estado_siprem VARCHAR NULL,
  fecha DATE NULL,
  hora VARCHAR NULL,
  eliminado boolean default false,
  fecha_registro timestamptz default current_timestamp
);

create table maestro_pagos_csr(
  id uuid primary key default gen_random_uuid(),
  accion text null,
  estado varchar null,
  se_paga varchar null,
  valor_unitario  double precision null,
  tipo_actividad varchar null,
  zona varchar null,
  eliminado boolean default false,
  fecha_registro timestamptz default current_timestamp
);
